datamodule:
  batch_size: 32
  normalizations:
  - class_path: viscy.transforms.ScaleIntensityRangePercentilesd
    init_args:
      b_max: 1.0
      b_min: 0.0
      keys:
      - RFP
      lower: 50
      upper: 99
  num_workers: 10
  patch_size:
  - 128
  - 128
  source_channel:
  - RFP
  z_range:
  - 24
  - 29
embedding:
  PCA_kwargs:
    n_components: 8
  PHATE_kwargs:
    decay: 40
    k: 5
    n_components: 2
    n_jobs: 15
  reductions:
  - PCA
  - PHATE
execution:
  overwrite: true
  save_config: true
  show_config: true
model:
  channel_reduction_methods:
    RFP: max
paths:
  data_path: /hpc/projects/intracellular_dashboard/organelle_dynamics/2024_02_04_A549_DENV_ZIKV_timelapse/8-train-test-split/registered_test.zarr
  output_path: /home/eduardo.hirata/repos/viscy/applications/benchmarking/DynaCLR/ImageNet/imagenet_infection_embeddings_3.zarr
  tracks_path: /hpc/projects/intracellular_dashboard/organelle_dynamics/2024_02_04_A549_DENV_ZIKV_timelapse/8-train-test-split/track_test.zarr
